dist: trusty
language: node_js
node_js:
  - "node"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      #- google-chrome-stable
      - google-chrome-beta # use this until stable is v59+

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: 
  - npm run travis