dist: trusty
language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - "node_modules"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable # v59+ is required for chrome-headless

script: 
  - yarn travis