language: node_js
node_js:
- "node"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - libfontconfig1
      - libstdc++6
      - lsb-base
      - google-chrome-stable

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start