dist: trusty
language: node_js
node_js:
  - "node"

cache:
  yarn: true
  directories:
    - "node_modules"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-beta # use this until stable is v59+

before_script:
  - export CHROME_BIN="google-chrome-beta"

script: 
  - yarn travis